# cibuildwheel.toml
[tool.cibuildwheel]
skip = "pp* cp36-* cp37-*"
build = "cp38-manylinux_x86_64 cp39-manylinux_x86_64 cp310-manylinux_x86_64 cp311-manylinux_x86_64 cp312-manylinux_x86_64 cp313-manylinux_x86_64"
manylinux-x86_64-image = "manylinux_2_28"

[tool.cibuildwheel.environment]
CC = "clang"
CXX = "clang++"
CMAKE_C_COMPILER = "/usr/bin/clang"
CMAKE_CXX_COMPILER = "/usr/bin/clang++"
CMAKE_BUILD_TYPE = "Release"
CMAKE_CXX_STANDARD = "17"

[tool.cibuildwheel]
before-build = "yum install -y clang llvm && pip install -r requirements.txt"